### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by KimJunHan** [linklab-uva/rosbag2nuscenes#11] opened 2024-07-31 23:57 UTC
I got an error about ros2bagstroage when I build it 

[ 16%] Building CXX object CMakeFiles/rosbag2nuscenes.dir/main.cpp.o
In file included from /home/jinwoo/rosbag2nuscenes/main.cpp:1:
/home/jinwoo/rosbag2nuscenes/include/rosbag2nuscenes/Bag2Scenes.hpp:23:10: fatal error: rosbag2_storage/storage_options.hpp: No such file or directory
   23 | #include <rosbag2_storage/storage_options.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/rosbag2nuscenes.dir/build.make:63: CMakeFiles/rosbag2nuscenes.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:219: CMakeFiles/rosbag2nuscenes.dir/all] Error 2
make: *** [Makefile:95: all] Error 2

How to solve it ?

**Comment by KimJunHan** [comment] 2024-08-01 03:32
I can not build your source.
How to do it let me know exact build guide

**Comment by KimJunHan** [comment] 2024-08-01 03:54
Ros2 Humble or foxy did you use it ??

**Comment by john-chrosniak** [comment] 2024-08-01 17:50
> Ros2 Humble or foxy did you use it ??

The library was designed to work with ROS2 Humble, Foxy may be usable but hasn't been tested.




> I got an error about ros2bagstroage when I build it
> 
> [ 16%] Building CXX object CMakeFiles/rosbag2nuscenes.dir/main.cpp.o In file included from /home/jinwoo/rosbag2nuscenes/main.cpp:1: /home/jinwoo/rosbag2nuscenes/include/rosbag2nuscenes/Bag2Scenes.hpp:23:10: fatal error: rosbag2_storage/storage_options.hpp: No such file or directory 23 | #include <rosbag2_storage/storage_options.hpp> | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ compilation terminated. make[2]: *** [CMakeFiles/rosbag2nuscenes.dir/build.make:63: CMakeFiles/rosbag2nuscenes.dir/main.cpp.o] Error 1 make[1]: *** [CMakeFiles/Makefile2:219: CMakeFiles/rosbag2nuscenes.dir/all] Error 2 make: *** [Makefile:95: all] Error 2
> 
> How to solve it ?

It looks like you're missing a ROS2 package, could you run `sudo apt install ros-<distro>-rosbag2*`?

**Comment by john-chrosniak** [comment] 2024-08-05 16:56
Closing as this was resolved in #12

**Closed as completed by john-chrosniak** 2024-08-05 16:56 UTC
